---
language: ruby
rvm:
- 1.9.3
install:
- bundle install
script:
- bundle exec foodcritic --epic-fail any .
- bundle exec rspec
notifications:
  email:
    recipients:
      - d.buch+modcloth-stingray-exec@modcloth.com
      - r.colton+modcloth-stingray-exec@modcloth.com
